<a href="https://colab.research.google.com/github/sjbriggsdev/dojo_bootcamp/blob/main/BRIGGS_Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [4]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [6]:
distance_array=np.array([100,200,400,800,1500,3000,5000,10000])

In [9]:
print(distance_array)

[  100   200   400   800  1500  3000  5000 10000]


3) Use the min() and max() functions to find the minimum and maximum distances

In [13]:
print(np.min(distance_array))
print(np.max(distance_array))

100
10000


4) To find the average distance, use the np.mean() function

In [14]:
print(np.mean(distance_array))

2625.0


5) use the sum() function to find the total distance

In [15]:
print(np.sum(distance_array))

21000


6) Another valuable function is the cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [17]:
print(np.cumsum(distance_array))

[  100   300   700  1500  3000  6000 11000 21000]


7) To round all of the values in an array, use np.round()

In [18]:
print(np.round(distance_array))

[  100   200   400   800  1500  3000  5000 10000]


8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [19]:
seconds_array=np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])
print(seconds_array)

[  10.62   21.34   48.25  113.43  233.96  506.53  866.17 1757.45]


9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [26]:
speed_array=np.array(0)
speed_array=distance_array/seconds_array
print(np.round(speed_array,4))


[9.4162 9.3721 8.2902 7.0528 6.4114 5.9227 5.7725 5.6901]


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [28]:
mph_array=np.array(0)
mph_array=speed_array*.00062*3600
print(np.round(mph_array,2))

[21.02 20.92 18.5  15.74 14.31 13.22 12.88 12.7 ]
